apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: site-cinema-vault
  namespace: cinegest-site
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-frontend
    kind: SecretStore
  target:
    name: site-cinema-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Variables d'environnement pour Next.js
        NEXT_PUBLIC_API_URL: "{{ .NEXT_PUBLIC_API_URL }}"
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "{{ .NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}"
  dataFrom:
    - extract:
        key: site-cinema/app
