apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-cinema
  namespace: cinegest-site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: cinegest-site-ratelimit@kubernetescrd,cinegest-site-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - maison-epouvante.nicolasbarbey.fr
      secretName: site-cinema-tls
  rules:
    - host: maison-epouvante.nicolasbarbey.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: site-cinema
                port:
                  number: 3000