apiVersion: v1
kind: Service
metadata:
  name: site-cinema
  namespace: cinegest-site
spec:
  selector:
    app: site-cinema
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP